language: bash
services: docker
install:
    - docker build -t moodle-db-mssql  .
script:
    - docker run --name test0 -e 'ACCEPT_EULA=Y' -e 'm@0dl3ing' -d moodle-db-mssql
      # We have to wait for SQL server to become available..
    - docker exec test0 /wait-for-mssql-to-come-up.sh
